services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: "mysql:8"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bibliotek
      MYSQL_DATABASE: bibliotek